const { Router } = require("express");
const PDFDocument = require("pdfkit");

const router = Router();

// ── Mock analytics data (same as analytics.js) ────────────────────────────────
const ANALYTICS = {
  totalAppointments: 847,
  avgDelay: 28,
  onTimeRate: 23,
  totalPointsAwarded: 42350,
  todayAppointments: 34,
  byHour: [
    { hour: 8,  avgDelay: 12, count: 8  },
    { hour: 9,  avgDelay: 18, count: 22 },
    { hour: 10, avgDelay: 35, count: 31 },
    { hour: 11, avgDelay: 42, count: 28 },
    { hour: 12, avgDelay: 38, count: 19 },
    { hour: 14, avgDelay: 15, count: 24 },
    { hour: 15, avgDelay: 28, count: 33 },
    { hour: 16, avgDelay: 45, count: 29 },
    { hour: 17, avgDelay: 52, count: 18 },
  ],
  byDay: [
    { day: "Lunes", dayEn: "Monday", avgDelay: 31, count: 142 },
    { day: "Martes", dayEn: "Tuesday", avgDelay: 24, count: 128 },
    { day: "Miércoles", dayEn: "Wednesday", avgDelay: 38, count: 156 },
    { day: "Jueves", dayEn: "Thursday", avgDelay: 27, count: 134 },
    { day: "Viernes", dayEn: "Friday", avgDelay: 44, count: 148 },
    { day: "Sábado", dayEn: "Saturday", avgDelay: 19, count: 89  },
  ],
  topDelays: [
    { appointment_id: "A-047", delay_minutes: 78, points_awarded: 780 },
    { appointment_id: "B-112", delay_minutes: 65, points_awarded: 650 },
    { appointment_id: "A-203", delay_minutes: 59, points_awarded: 590 },
    { appointment_id: "C-088", delay_minutes: 54, points_awarded: 540 },
    { appointment_id: "B-031", delay_minutes: 51, points_awarded: 510 },
  ],
};

const PRIMARY = "#7F77DD";
const INK = "#1A1A2E";
const GRAY = "#6B7280";
const GREEN = "#22C55E";

function drawHRule(doc, y, color = "#E5E7EB") {
  doc.save().strokeColor(color).lineWidth(0.5).moveTo(50, y).lineTo(545, y).stroke().restore();
}

function sectionHeader(doc, title, y) {
  doc.save()
    .rect(50, y, 495, 20)
    .fillColor("#F8F7FF")
    .fill()
    .restore();
  doc.fillColor(PRIMARY).fontSize(9).font("Helvetica-Bold")
    .text(title.toUpperCase(), 56, y + 6, { width: 480 });
  doc.fillColor(INK);
  return y + 28;
}

const pdfText = {
  es: {
    title: 'Reporte de Analytics',
    subtitle: 'Clínica Demo — HORMI',
    generated: 'Generado el',
    totalAppointments: 'Turnos totales',
    avgDelay: 'Demora promedio',
    onTimeRate: 'Tasa puntualidad',
    pointsIssued: 'Puntos emitidos',
    delayByHour: 'Demoras por hora del día',
    delayByDay: 'Demoras por día de la semana',
    recentDelays: 'Últimas demoras registradas',
    appointment: 'Turno',
    delay: 'Demora',
    points: 'Puntos',
    footer: 'Generado por HORMI — Powered by Avalanche',
    hour: 'Hora',
    avgDelayShort: 'Demora prom.',
    appointmentsCount: 'Turnos',
    index: 'Índice',
    day: 'Día',
    severity: 'Severidad',
    sevSevere: 'Severa',
    sevModerate: 'Moderada',
    sevMinor: 'Leve',
    period: 'Periodo: últimos 30 días · Fuente: Avalanche Fuji + datos históricos',
    page: 'Página',
    of: 'de'
  },
  en: {
    title: 'Analytics Report',
    subtitle: 'Demo Clinic — HORMI',
    generated: 'Generated on',
    totalAppointments: 'Total appointments',
    avgDelay: 'Average delay',
    onTimeRate: 'On-time rate',
    pointsIssued: 'Points issued',
    delayByHour: 'Delays by hour of day',
    delayByDay: 'Delays by day of week',
    recentDelays: 'Recent delays registered',
    appointment: 'Appointment',
    delay: 'Delay',
    points: 'Points',
    footer: 'Generated by HORMI — Powered by Avalanche',
    hour: 'Hour',
    avgDelayShort: 'Avg. delay',
    appointmentsCount: 'Appointments',
    index: 'Index',
    day: 'Day',
    severity: 'Severity',
    sevSevere: 'Severe',
    sevModerate: 'Moderate',
    sevMinor: 'Minor',
    period: 'Period: Last 30 days · Source: Avalanche Fuji + historical data',
    page: 'Page',
    of: 'of'
  }
};

/**
 * GET /api/reports/clinic/pdf
 * Generates and streams a PDF analytics report.
 */
router.get("/clinic/pdf", (req, res) => {
  const lang = req.query.lang || 'es';
  const t = pdfText[lang] || pdfText.es;

  const now = new Date();
  const dateStr = now.toLocaleDateString(lang === 'es' ? "es-AR" : "en-US", { day: "2-digit", month: "long", year: "numeric" });
  const fileDate = now.toISOString().slice(0, 10);

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="reporte-clinica-${fileDate}.pdf"`);

  const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
  doc.pipe(res);

  // ── HEADER ─────────────────────────────────────────────────────────────────
  // Purple bar
  doc.rect(0, 0, 595, 70).fillColor(PRIMARY).fill();

  // Logo text
  doc.fillColor("white").fontSize(22).font("Helvetica-Bold").text("⏱ HORMI", 50, 22);
  doc.fontSize(9).font("Helvetica").fillColor("rgba(255,255,255,0.8)")
    .text(`${t.generated} ${dateStr} · Powered by Avalanche`, 50, 48);

  // ── TITLE ──────────────────────────────────────────────────────────────────
  doc.fillColor(INK).fontSize(16).font("Helvetica-Bold")
    .text(`${t.title} — ${t.subtitle.split(' — ')[0]}`, 50, 90);
  doc.fontSize(9).font("Helvetica").fillColor(GRAY)
    .text(t.period, 50, 112);

  drawHRule(doc, 128);

  // ── KPIs ───────────────────────────────────────────────────────────────────
  let y = 138;
  const kpiTitle = lang === 'en' ? 'Main KPIs' : 'KPIs Principales';
  doc.fillColor(INK).fontSize(11).font("Helvetica-Bold").text(kpiTitle, 50, y);
  y += 16;

  const kpis = [
    { label: t.totalAppointments, value: ANALYTICS.totalAppointments.toLocaleString("es-AR"), color: INK },
    { label: t.avgDelay,          value: `${ANALYTICS.avgDelay} min`,                          color: INK },
    { label: t.onTimeRate,        value: `${ANALYTICS.onTimeRate}%`,                           color: GREEN },
    { label: t.pointsIssued,      value: ANALYTICS.totalPointsAwarded.toLocaleString("es-AR"), color: PRIMARY },
  ];

  const boxW = 115;
  const boxH = 52;
  const gap  = 10;
  let bx = 50;

  for (const kpi of kpis) {
    doc.save().rect(bx, y, boxW, boxH).fillColor("#F8F7FF").strokeColor("#E5E7EB")
      .lineWidth(0.5).fillAndStroke().restore();
    doc.fillColor(GRAY).fontSize(7.5).font("Helvetica-Bold")
      .text(kpi.label.toUpperCase(), bx + 8, y + 8, { width: boxW - 16 });
    doc.fillColor(kpi.color).fontSize(18).font("Helvetica-Bold")
      .text(kpi.value, bx + 8, y + 22, { width: boxW - 16 });
    bx += boxW + gap;
  }

  y += boxH + 20;
  drawHRule(doc, y);
  y += 12;

  // ── DEMORA POR HORA ────────────────────────────────────────────────────────
  y = sectionHeader(doc, t.delayByHour, y);

  // Table header
  const cols = [50, 120, 250, 380];
  doc.fontSize(8).font("Helvetica-Bold").fillColor(GRAY);
  doc.text(t.hour,        cols[0], y);
  doc.text(t.avgDelayShort, cols[1], y);
  doc.text(t.appointmentsCount, cols[2], y);
  doc.text(t.index,      cols[3], y);
  y += 14;
  drawHRule(doc, y, "#D1D5DB");
  y += 6;

  const maxHourDelay = Math.max(...ANALYTICS.byHour.map((h) => h.avgDelay));

  for (const row of ANALYTICS.byHour) {
    const barW = Math.round((row.avgDelay / maxHourDelay) * 100);
    doc.fontSize(8.5).font("Helvetica").fillColor(INK);
    doc.text(`${row.hour}:00`, cols[0], y);
    doc.text(`${row.avgDelay} min`,    cols[1], y);
    doc.text(`${row.count}`,    cols[2], y);
    // Mini bar
    doc.save().rect(cols[3], y + 2, barW, 7).fillColor(PRIMARY).fill().restore();
    y += 15;
    if (y > 720) { doc.addPage(); y = 50; }
  }

  y += 8;
  drawHRule(doc, y);
  y += 12;

  // ── DEMORA POR DÍA ─────────────────────────────────────────────────────────
  y = sectionHeader(doc, t.delayByDay, y);

  doc.fontSize(8).font("Helvetica-Bold").fillColor(GRAY);
  doc.text(t.day,         cols[0], y);
  doc.text(t.avgDelayShort, cols[1], y);
  doc.text(t.appointmentsCount, cols[2], y);
  doc.text(t.index,       cols[3], y);
  y += 14;
  drawHRule(doc, y, "#D1D5DB");
  y += 6;

  const maxDayDelay = Math.max(...ANALYTICS.byDay.map((d) => d.avgDelay));

  for (const row of ANALYTICS.byDay) {
    const barW = Math.round((row.avgDelay / maxDayDelay) * 100);
    doc.fontSize(8.5).font("Helvetica").fillColor(INK);
    doc.text(lang === 'en' ? row.dayEn : row.day,      cols[0], y);
    doc.text(`${row.avgDelay} min`,    cols[1], y);
    doc.text(`${row.count}`,    cols[2], y);
    doc.save().rect(cols[3], y + 2, barW, 7).fillColor("#9B8FE8").fill().restore();
    y += 15;
    if (y > 720) { doc.addPage(); y = 50; }
  }

  y += 8;
  drawHRule(doc, y);
  y += 12;

  // ── TOP 5 DEMORAS ──────────────────────────────────────────────────────────
  y = sectionHeader(doc, t.recentDelays, y);

  doc.fontSize(8).font("Helvetica-Bold").fillColor(GRAY);
  doc.text(t.appointment,  cols[0], y);
  doc.text(t.delay,        cols[1], y);
  doc.text("WaitPoints",   cols[2], y);
  doc.text(t.severity,     cols[3], y);
  y += 14;
  drawHRule(doc, y, "#D1D5DB");
  y += 6;

  for (const row of ANALYTICS.topDelays) {
    const isSevere = row.delay_minutes >= 60;
    const isMod = row.delay_minutes >= 30;
    const sev = isSevere ? t.sevSevere : isMod ? t.sevModerate : t.sevMinor;
    const sevColor = isSevere ? "#EF4444" : isMod ? "#F97316" : "#EAB308";
    
    doc.fontSize(8.5).font("Helvetica").fillColor(INK);
    doc.text(row.appointment_id,         cols[0], y);
    doc.text(`${row.delay_minutes} min`, cols[1], y);
    doc.text(`${row.points_awarded} WP`, cols[2], y);
    doc.fillColor(sevColor).font("Helvetica-Bold").text(sev.toUpperCase(), cols[3], y);
    doc.fillColor(INK).font("Helvetica");
    y += 15;
  }

  y += 16;
  drawHRule(doc, y);

  // ── FOOTER ─────────────────────────────────────────────────────────────────
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    doc.save()
      .rect(0, 800, 595, 42)
      .fillColor("#F8F7FF")
      .fill()
      .restore();
    doc.fillColor(GRAY).fontSize(7.5).font("Helvetica")
      .text(
        `${t.footer} · ${dateStr} · ${t.page} ${i + 1} ${t.of} ${pages.count}`,
        50, 812, { width: 495, align: "center" }
      );
  }

  doc.end();
});

module.exports = router;
